# 1. 데이터 확인하기

In [24]:
import pandas as pd

In [26]:
titanic_df = pd.read_csv('/aiffel/data/titanic.csv')

In [27]:
titanic_df

,Pclass,Name,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,S,0,1912-01-12
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,C,1,1912-03-29
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,S,1,1912-02-23
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,NaN,1,0,113803,S,1,1912-03-28
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,S,0,1912-04-03
...,...,...,...,...,...,...,...,...,...,...
880,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,S,0,1912-01-29
881,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,S,1,1912-03-30
882,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,S,0,1912-04-07
883,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,C,1,1912-03-01
884,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,Q,0,1912-03-05

In [29]:
titanic_df.head()

,Pclass,Name,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,S,0,1912-01-12
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,C,1,1912-03-29
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,S,1,1912-02-23
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,NaN,1,0,113803,S,1,1912-03-28
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,S,0,1912-04-03

In [30]:
# DataFrame 또는 Series 객체의 끝에서부터 지정된 수의 행을 반환
titanic_df.tail()

,Pclass,Name,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
880,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,S,0,1912-01-29
881,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,S,1,1912-03-30
882,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,S,0,1912-04-07
883,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,C,1,1912-03-01
884,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,Q,0,1912-03-05

In [15]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 885 entries, 0 to 884
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Pclass       885 non-null    int64
 1   Name         885 non-null    object
 2   Gendr        885 non-null    object
 3   Age          879 non-null    float64
 4   SibSp        885 non-null    int64
 5   Parch        885 non-null    int64
 6   Ticket       885 non-null    object
 7   Embarked     883 non-null    object
 8   Survived     885 non-null    int64
 9   ticket_date  885 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 69.3+ KB

In [16]:
#DataFrame 또는 Series 객체에 대한 요약 통계를 제공
titanic_df.describe()

           Pclass         Age       SibSp       Parch    Survived
count  885.000000  879.000000  885.000000  885.000000  885.000000
mean     2.311864   29.679181    0.525424    0.377401    0.377401
std      0.836069   13.559664    1.109746    0.805768    0.485011
min      1.000000    1.000000    0.000000    0.000000    0.000000
25%      2.000000   22.000000    0.000000    0.000000    0.000000
50%      3.000000   28.000000    0.000000    0.000000    0.000000
75%      3.000000   35.000000    1.000000    0.000000    1.000000
max      3.000000  145.000000    8.000000    6.000000    1.000000

In [17]:
# Pandas Series 형태
titanic_df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
880                                Montvila, Rev. Juozas
881                         Graham, Miss. Margaret Edith
882             Johnston, Miss. Catherine Helen "Carrie"
883                                Behr, Mr. Karl Howell
884                                  Dooley, Mr. Patrick
Name: Name, Length: 885, dtype: object

In [18]:
# DataFrame 형태
titanic_df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)   NaN
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
880                              Montvila, Rev. Juozas  27.0
881                       Graham, Miss. Margaret Edith  19.0
882           Johnston, Miss. Catherine Helen "Carrie"  28.0
883                              Behr, Mr. Karl Howell  26.0
884                                Dooley, Mr. Patrick  32.0

[885 rows x 2 columns]

In [19]:
# Series -> DataFrame
pd.DataFrame(titanic_df['Name'])

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
880                              Montvila, Rev. Juozas
881                       Graham, Miss. Margaret Edith
882           Johnston, Miss. Catherine Helen "Carrie"
883                              Behr, Mr. Karl Howell
884                                Dooley, Mr. Patrick

[885 rows x 1 columns]

In [21]:
# Series -> DataFrame -> Series (인덱싱 필요)
# 실제로 사용할 일은 없을 것
pd.Series(pd.DataFrame(titanic_df['Name'])['Name'])

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
880                                Montvila, Rev. Juozas
881                         Graham, Miss. Margaret Edith
882             Johnston, Miss. Catherine Helen "Carrie"
883                                Behr, Mr. Karl Howell
884                                  Dooley, Mr. Patrick
Name: Name, Length: 885, dtype: object

In [22]:
import numpy as np

# 컴퓨터 입장에서 데이터를 다룰 때 용이
# pandas에 비해 훨씬 빠르고 포맷이 단순하여 연산이 용이

In [31]:
np.array(titanic_df)

array([[3, 'Braund, Mr. Owen Harris', 'male', ..., 'S', 0, '1912-01-12'],
       [1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
        'female', ..., 'C', 1, '1912-03-29'],
       [3, 'Heikkinen, Miss. Laina', 'female', ..., 'S', 1, '1912-02-23'],
       ...,
       [3, 'Johnston, Miss. Catherine Helen "Carrie"', 'female', ...,
        'S', 0, '1912-04-07'],
       [1, 'Behr, Mr. Karl Howell', 'male', ..., 'C', 1, '1912-03-01'],
       [3, 'Dooley, Mr. Patrick', 'male', ..., 'Q', 0, '1912-03-05']],
      dtype=object)

# 2. 불필요한 컬럼 삭제 (Dropping columns), 누락된 결측치 처리 (Missing values)

In [37]:
# 중복 데이터 처리 부분에서 활용
titanic_df[titanic_df.duplicated()]

,Pclass,Name,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
25,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,S,0,1912-03-14
632,3,"Skoog, Miss. Mabel",female,9.0,3,2,347088,S,0,1912-03-16
714,1,"Endres, Miss. Caroline Louise",female,38.0,0,0,PC 17757,C,1,1912-03-14

In [38]:
# 중복 데이터 처리 부분에서 활용
titanic_df[titanic_df['Name'] == 'Palsson, Miss. Torborg Danira']

,Pclass,Name,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
24,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,S,0,1912-03-14
25,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,S,0,1912-03-14

In [39]:
# 중복 데이터 처리 부분에서 활용
titanic_df = titanic_df.drop_duplicates()

### 'Name' 컬럼 제거

In [32]:
# 파라미터 axis=축 -> 기본값 0
# 컬럼 단위로 찾기 위해 axis=1로 지정

titanic_df.drop('Name', axis = 1)

# 컬럼 2개 이상 지정 시, 리스트로 묶어줘야 한다.
# titanic_df.drop(['Pclass', 'Age'], axis = 1)

# drop된 결과만 보여줄 뿐이지, 원래 데이터에 덮어씌워지는 것은 아니다.

,Pclass,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
0,3,male,22.0,1,0,A/5 21171,S,0,1912-01-12
1,1,female,38.0,1,0,PC 17599,C,1,1912-03-29
2,3,female,26.0,0,0,STON/O2. 3101282,S,1,1912-02-23
3,1,female,NaN,1,0,113803,S,1,1912-03-28
4,3,male,35.0,0,0,373450,S,0,1912-04-03
...,...,...,...,...,...,...,...,...,...
880,2,male,27.0,0,0,211536,S,0,1912-01-29
881,1,female,19.0,0,0,112053,S,1,1912-03-30
882,3,female,28.0,1,2,W./C. 6607,S,0,1912-04-07
883,1,male,26.0,0,0,111369,C,1,1912-03-01
884,3,male,32.0,0,0,370376,Q,0,1912-03-05

In [33]:
# 원본 데이터를 완전히 업데이트하려면
# 방법 1
# titanic_df = titanic_df.drop('Name', axis = 1)

In [34]:
# 방법 2
# iplace 기본값은 False
titanic_df.drop('Name', axis = 1, inplace = True)

In [35]:
titanic_df.head()

,Pclass,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
0,3,male,22.0,1,0,A/5 21171,S,0,1912-01-12
1,1,female,38.0,1,0,PC 17599,C,1,1912-03-29
2,3,female,26.0,0,0,STON/O2. 3101282,S,1,1912-02-23
3,1,female,NaN,1,0,113803,S,1,1912-03-28
4,3,male,35.0,0,0,373450,S,0,1912-04-03

In [36]:
# 인덱스(행) 이름 변경해 보기

# temp = titanic_df.head().copy()
# temp.index = ['a', 'b', 'c', 'd', 'e']

### 결측치 처리하기

loc vs iloc

In [40]:
# isna(): 결측치 확인하는 pandas 메소드
titanic_df.isna()

,Pclass,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
880,False,False,False,False,False,False,False,False,False
881,False,False,False,False,False,False,False,False,False
882,False,False,False,False,False,False,False,False,False
883,False,False,False,False,False,False,False,False,False
884,False,False,False,False,False,False,False,False,False

In [41]:
# 각 컬럼별 결측치 개수 확인 - True는 1이므로
titanic_df.isna().sum()

Pclass         0
Gendr          0
Age            6
SibSp          0
Parch          0
Ticket         0
Embarked       2
Survived       0
ticket_date    0
dtype: int64

In [42]:
# 각 컬럼별 결측치 비율 확인
titanic_df.isna().mean()

Pclass         0.00000
Gendr          0.00000
Age            0.00678
SibSp          0.00000
Parch          0.00000
Ticket         0.00000
Embarked       0.00226
Survived       0.00000
ticket_date    0.00000
dtype: float64

In [43]:
titanic_df[titanic_df['Age'].isna()]

,Pclass,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
3,1,female,NaN,1,0,113803,S,1,1912-03-28
106,3,male,NaN,0,0,312991,S,1,1912-01-27
156,3,male,NaN,0,0,SOTON/OQ 392090,S,0,1912-04-01
185,3,female,NaN,1,0,370365,Q,1,1912-03-25
213,3,male,NaN,1,0,367229,Q,0,1912-02-12
241,2,male,NaN,0,0,W./C. 14263,S,0,1912-01-31

In [44]:
age_na_index = titanic_df[titanic_df['Age'].isna()].index

In [45]:
age_na_index

Int64Index([3, 106, 156, 185, 213, 241], dtype='int64')

In [46]:
embarked_na_index = titanic_df[titanic_df['Embarked'].isna()].index
embarked_na_index

Int64Index([15, 322], dtype='int64')

In [49]:
titanic_df.loc[age_na_index]

,Pclass,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
3,1,female,NaN,1,0,113803,S,1,1912-03-28
106,3,male,NaN,0,0,312991,S,1,1912-01-27
156,3,male,NaN,0,0,SOTON/OQ 392090,S,0,1912-04-01
185,3,female,NaN,1,0,370365,Q,1,1912-03-25
213,3,male,NaN,1,0,367229,Q,0,1912-02-12
241,2,male,NaN,0,0,W./C. 14263,S,0,1912-01-31

In [48]:
titanic_df.loc[embarked_na_index]

,Pclass,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
15,2,female,55.0,0,0,248706,NaN,1,1912-03-05
322,3,male,28.0,8,2,CA. 2343,NaN,0,1912-03-26

### NaN 값이 있는 행 제거하기 (결측치 제거)

In [53]:
len(titanic_df)

885

In [51]:
# 방법 1. 노이즈가 끼는 것을 막기 위해 결측치가 있는 모든 행 제거
titanic_df.dropna()

# 데이터의 크기가 충분히 크지 않으면, 정보의 유실이 커지기 때문에 충분히 고려해야 함

,Pclass,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
0,3,male,22.0,1,0,A/5 21171,S,0,1912-01-12
1,1,female,38.0,1,0,PC 17599,C,1,1912-03-29
2,3,female,26.0,0,0,STON/O2. 3101282,S,1,1912-02-23
4,3,male,35.0,0,0,373450,S,0,1912-04-03
5,3,male,28.0,0,0,330877,Q,0,1912-03-30
...,...,...,...,...,...,...,...,...,...
880,2,male,27.0,0,0,211536,S,0,1912-01-29
881,1,female,19.0,0,0,112053,S,1,1912-03-30
882,3,female,28.0,1,2,W./C. 6607,S,0,1912-04-07
883,1,male,26.0,0,0,111369,C,1,1912-03-01
884,3,male,32.0,0,0,370376,Q,0,1912-03-05

In [55]:
# 방법 2. 컬럼을 지정하고 싶을 때
# 하나의 컬럼만 사용하더라도 리스트 형태로 정의해야 함
titanic_df.dropna(subset = ['Embarked'])

,Pclass,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
0,3,male,22.0,1,0,A/5 21171,S,0,1912-01-12
1,1,female,38.0,1,0,PC 17599,C,1,1912-03-29
2,3,female,26.0,0,0,STON/O2. 3101282,S,1,1912-02-23
3,1,female,NaN,1,0,113803,S,1,1912-03-28
4,3,male,35.0,0,0,373450,S,0,1912-04-03
...,...,...,...,...,...,...,...,...,...
880,2,male,27.0,0,0,211536,S,0,1912-01-29
881,1,female,19.0,0,0,112053,S,1,1912-03-30
882,3,female,28.0,1,2,W./C. 6607,S,0,1912-04-07
883,1,male,26.0,0,0,111369,C,1,1912-03-01
884,3,male,32.0,0,0,370376,Q,0,1912-03-05


데이터가 많지 않은 경우에 결측치를 모두 제거하는 것은 좋지 않기 때문에,
해당 예제에서는 결측치를 채워줄 것이다.

In [57]:
titanic_df['Age'].mean()

29.679180887372013

In [59]:
titanic_df['Age'].median()

28.0

In [61]:
# 일반적으로 median을 사용한다.
# mean의 경우, outlier 때문에 값이 치우칠 여지가 있다.

titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].median())

In [63]:
titanic_df.loc[age_na_index]

,Pclass,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
3,1,female,28.0,1,0,113803,S,1,1912-03-28
106,3,male,28.0,0,0,312991,S,1,1912-01-27
156,3,male,28.0,0,0,SOTON/OQ 392090,S,0,1912-04-01
185,3,female,28.0,1,0,370365,Q,1,1912-03-25
213,3,male,28.0,1,0,367229,Q,0,1912-02-12
241,2,male,28.0,0,0,W./C. 14263,S,0,1912-01-31

In [64]:
# 카테고리형 데이터의 결측치는 평균을 구할 수 없다.

# 방법 1. 특정 값이 다수의 역할을 하고 있을 때 (99% 값이 S인 경우)
titanic_df['Embarked'].value_counts()

S    640
C    166
Q     77
Name: Embarked, dtype: int64

In [66]:
640 / 885
# 해당 예제에서는 약 72%로 방법 1이 최선은 아닐 수 있다.

0.7231638418079096

In [ ]:
# 방법 2. null값임을 정의해주는 별도의 값으로 채우기
# unknown, N/A 등

titanic_df['Embarked'].fillna('N/A')

In [67]:
# 해당 예제에서는 null값을 따로 정의해두는 게 큰 의미는 없을 것 같다.
# 따라서 72%의 확률을 믿고 채우기

titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')

특정 컬럼에 결측치가 많은 경우(50%, 70% 이상 등) 컬럼 자체를 제거하는 것도 방법이다.